title: 10 Tips for Healthy Life
theme: minima
author: Khun_Cho_lwin
email: KhunChoLwin.2019@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Eat a variety of foods
Base your diet on plenty of foods rich in carbohydrates
Replace saturated with unsaturated fat
Enjoy plenty of fruits and vegetables
Reduce salt and sugar intake
Eat regularly, control the portion size
Drink plenty of fluids
Maintain a healthy body weight
Get on the move, make it a habit!
Start now! And keep changing gradually.
# https://www.eufic.org/en/healthy-living/article/10-healthy-lifestyle-tips-for-adults
